name: Building Website with Pelican

on:
  push:
    branches:
      - source
  deployment:
    branches:
      - source

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    
    - name: Set up Python 3.x
      uses: actions/setup-python@v1
      with:
        python-version: 3.7
    
    - name: Set up Node 
      uses: actions/setup-node@v1
      with:
        node-version: 12

    - uses: actions/cache@v1
      id: cache
      with:
        path: ./.venv
        key: ${{ runner.os }}-${{ hashFiles('**/Pipfile.lock') }}
    
    - name: Install dependencies
      env:
        PIPENV_IGNORE_VIRTUALENVS: 1
        PIPENV_VENV_IN_PROJECT: 1
        ENVIRONMENT: PRODUCTION
      run: |
        python -m pip install --upgrade pip
        pip install pipenv
        pipenv install --ignore-pipfile
        npm install -g sass
        
    - name: Build Website
      run: pipenv run build
      
    - name: Deploy
      uses: peaceiris/actions-gh-pages@v2.5.0
      env:
        PERSONAL_TOKEN: ${{ secrets.PERSONAL_TOKEN }}
        PUBLISH_BRANCH: master
        PUBLISH_DIR: ./output