name: Building Website with Pelican

on:
  push:
    branches:    
      - content   

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    
    - name: Trigger Build
      run: bash .publish.sh ${{ secrets.PERSONAL_TOKEN }}